# Site Settings
title: "StrataFlux Energy"
title_separator: "|"
subtitle: " "
description: "Expert modelling for CO₂ storage, H₂ storage, EOR, and reservoir performance. Hands-on open-source training for students."
#baseurl: " " #"/strataflux-energy"         # must match your repo name for project sites, i.e. "_config.yml" directly/folder
url: "https://stratafluxenergy.com"   # "https://law17.github.io"
repository: "law17/strataflux-energy"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Site Settings
locale: "en-US"
logo: "/assets/images/logo.png"
masthead_title: "StrataFlux Energy"
breadcrumbs: true
search: false

# Plugins (jekyll-remote-theme is essential!)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      # Add author details here
      author:
        name: "Emma"
        avatar: "/assets/images/logo.png"
        bio: "Subsurface modelling specialist. Open‑source enthusiast."
        location: "city, contry"
        email: "blessv2013@gmail.com"

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Remove feed at footnote
atom_feed:
  hide: true

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - _pages
  - googlea42bca6c8d119a30.html

# Footer
footer:
  links:
    - label: "About"
      icon: "fas fa-info-circle"
      url: "/about/"
    - label: "Services"
      icon: "fas fa-cogs"  
      url: "/services/"      
   # - label: "Careers"
   #   icon: "fas fa-briefcase"
   #   url: "/careers/"   
    - label: "Contact"
      icon: "fas fa-envelope"
      url: "/contact/"
    - label: "Privacy notice"
      icon: "fas fa-cogs"
      url: "/privacy/"

